// Escolas Municipais Oficiais de Gonçalves Dias - MA (2015 a 2025)
window.ESCOLAS_MARANHAO_OFICIAL = [
  {
    "id": "esc_1",
    "inep": "21192544",
    "nome": "UE ANITA FURTADO",
    "municipio": "Gonçalves Dias",
    "uf": "MA",
    "rede": "Municipal",
    "localizacao": "Sede Urbana",
    "diretor": "Profª Ana Rita Anita Furtado",
    "alunos_total": 39,
    "turmas_total": 2,
    "ideb_2021": 4.8,
    "ideb_2023": 5,
    "ideb_2025_meta": 5.2,
    "ideb_2025_observado": 5.4
  },
  {
    "id": "esc_2",
    "inep": "21286973",
    "nome": "UI ALDENORA DE ARAÚJO CRUZ",
    "municipio": "Gonçalves Dias",
    "uf": "MA",
    "rede": "Municipal",
    "localizacao": "Sede Urbana",
    "diretor": "Profª Aldenora Araújo Cruz",
    "alunos_total": 232,
    "turmas_total": 10,
    "ideb_2021": 4.8,
    "ideb_2023": 5,
    "ideb_2025_meta": 5.2,
    "ideb_2025_observado": 5.2
  },
  {
    "id": "esc_3",
    "inep": "21128774",
    "nome": "UE ANISIO GOMES",
    "municipio": "Gonçalves Dias",
    "uf": "MA",
    "rede": "Municipal",
    "localizacao": "Zona Rural",
    "diretor": "Profª Francisca Anísio Gomes",
    "alunos_total": 31,
    "turmas_total": 3,
    "ideb_2021": 4.8,
    "ideb_2023": 5,
    "ideb_2025_meta": 5.2,
    "ideb_2025_observado": 4.8
  },
  {
    "id": "esc_4",
    "inep": "21286990",
    "nome": "UI ANTONIO GONÇALVES DIAS",
    "municipio": "Gonçalves Dias",
    "uf": "MA",
    "rede": "Municipal",
    "localizacao": "Zona Rural",
    "diretor": "Prof. Raimundo José Dias",
    "alunos_total": 27,
    "turmas_total": 3,
    "ideb_2021": 4.8,
    "ideb_2023": 5,
    "ideb_2025_meta": 5.2,
    "ideb_2025_observado": 4.9
  },
  {
    "id": "esc_5",
    "inep": "21128120",
    "nome": "U I BASILIO ALVES",
    "municipio": "Gonçalves Dias",
    "uf": "MA",
    "rede": "Municipal",
    "localizacao": "Zona Rural",
    "diretor": "Prof. José Basílio Alves",
    "alunos_total": 59,
    "turmas_total": 3,
    "ideb_2021": 4.8,
    "ideb_2023": 5,
    "ideb_2025_meta": 5.2,
    "ideb_2025_observado": 5
  }
];
